apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snapcal.fullname" . }}-env
  labels:
    {{- include "snapcal.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snapcal.fullname" . }}-secrets
  labels:
    {{- include "snapcal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | default "snapcal" | quote }}
