module.exports = {
  apps: [
    {
      name: 'snapcal-web',
      cwd: '/root/snapcal-ai-health-coach/apps/web',
      script: 'server.cjs',
      interpreter: 'node',
      env: { NODE_ENV: 'production', PORT: 5173, API_URL: 'http://127.0.0.1:3000' },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'snapcal-web-staging',
      cwd: '/root/snapcal-ai-health-coach/apps/web',
      script: 'server.cjs',
      interpreter: 'node',
      env: { NODE_ENV: 'staging', PORT: 5174, API_URL: 'http://127.0.0.1:3001' },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'snapcal-web-test',
      cwd: '/root/snapcal-ai-health-coach/apps/web',
      script: 'server.cjs',
      interpreter: 'node',
      env: { NODE_ENV: 'test', PORT: 5175, API_URL: 'http://127.0.0.1:3005' },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'snapcal-api',
      cwd: '/root/snapcal-ai-health-coach/apps/api',
      script: 'start-with-env.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'production', PORT: 3000, AGENT_SERVICE_URL: 'http://localhost:3101' },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'snapcal-api-staging',
      cwd: '/root/snapcal-ai-health-coach/apps/api',
      script: 'start-with-env.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'staging', PORT: 3001, AGENT_SERVICE_URL: 'http://localhost:3102' },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'snapcal-api-test',
      cwd: '/root/snapcal-ai-health-coach/apps/api',
      script: 'start-with-env.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'test', PORT: 3005, AGENT_SERVICE_URL: 'http://localhost:3105' },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'snapcal-agent',
      cwd: '/root/snapcal-ai-health-coach/apps/agent',
      script: 'start-with-env.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'production', PORT: 3101 },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'snapcal-agent-staging',
      cwd: '/root/snapcal-ai-health-coach/apps/agent',
      script: 'start-with-env.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'staging', PORT: 3102 },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'snapcal-agent-test',
      cwd: '/root/snapcal-ai-health-coach/apps/agent',
      script: 'start-with-env.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'test', PORT: 3105 },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'snapcal-telegram-bot',
      cwd: '/root/snapcal-ai-health-coach/apps/telegram-bot',
      script: 'start-with-env.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'production', USE_POLLING: 'true', SNAPCAL_API_URL: 'http://localhost:3000/api/v1', SNAPCAL_AGENT_URL: 'http://localhost:3101' },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '150M',
    },
    {
      name: 'snapcal-telegram-bot-staging',
      cwd: '/root/snapcal-ai-health-coach/apps/telegram-bot',
      script: 'start-with-env.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'staging', USE_POLLING: 'true', SNAPCAL_API_URL: 'http://localhost:3001/api/v1', SNAPCAL_AGENT_URL: 'http://localhost:3102' },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '150M',
    },
    {
      name: 'snapcal-telegram-bot-test',
      cwd: '/root/snapcal-ai-health-coach/apps/telegram-bot',
      script: 'start-with-env.mjs',
      interpreter: 'node',
      env: { NODE_ENV: 'test', USE_POLLING: 'true', SNAPCAL_API_URL: 'http://localhost:3005/api/v1', SNAPCAL_AGENT_URL: 'http://localhost:3105' },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '150M',
    },
    {
      name: 'snapcal-admin',
      cwd: '/root/snapcal-ai-health-coach/apps/admin',
      script: 'server.cjs',
      interpreter: 'node',
      env: { NODE_ENV: 'production', PORT: 5176, API_URL: 'http://127.0.0.1:3000' },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '150M',
    },
  ],
};
